var searchData=
[
  ['calcdamageinfo',['CalcDamageInfo',['../structCalcDamageInfo.html',1,'']]],
  ['callback',['Callback',['../classMaNGOS_1_1Callback.html',1,'MaNGOS']]],
  ['callback_3c_20class_20_3e',['Callback&lt; Class &gt;',['../classMaNGOS_1_1Callback_3_01Class_01_4.html',1,'MaNGOS']]],
  ['callback_3c_20class_2c_20paramtype1_20_3e',['Callback&lt; Class, ParamType1 &gt;',['../classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_01_4.html',1,'MaNGOS']]],
  ['callback_3c_20class_2c_20paramtype1_2c_20paramtype2_20_3e',['Callback&lt; Class, ParamType1, ParamType2 &gt;',['../classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_00_01ParamType2_01_4.html',1,'MaNGOS']]],
  ['callback_3c_20class_2c_20paramtype1_2c_20paramtype2_2c_20paramtype3_20_3e',['Callback&lt; Class, ParamType1, ParamType2, ParamType3 &gt;',['../classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_00_01ParamType2_00_01ParamType3_01_4.html',1,'MaNGOS']]],
  ['callofhelpcreatureinrangedo',['CallOfHelpCreatureInRangeDo',['../classMaNGOS_1_1CallOfHelpCreatureInRangeDo.html',1,'MaNGOS']]],
  ['camellia_5fkey_5fst',['camellia_key_st',['../structcamellia__key__st.html',1,'']]],
  ['camera',['Camera',['../classCamera.html',1,'']]],
  ['cameradistworker',['CameraDistWorker',['../structMaNGOS_1_1CameraDistWorker.html',1,'MaNGOS']]],
  ['cannibalizeobjectcheck',['CannibalizeObjectCheck',['../classMaNGOS_1_1CannibalizeObjectCheck.html',1,'MaNGOS']]],
  ['capsule',['Capsule',['../classG3D_1_1Capsule.html',1,'G3D']]],
  ['caravanmember',['CaravanMember',['../structCaravanMember.html',1,'']]],
  ['cast_5fkey_5fst',['cast_key_st',['../structcast__key__st.html',1,'']]],
  ['ccs_5fheader_5fst',['ccs_header_st',['../structccs__header__st.html',1,'']]],
  ['celebras_5fthe_5fcursedai',['celebras_the_cursedAI',['../structcelebras__the__cursedAI.html',1,'']]],
  ['celebrasspiritai',['celebrasSpiritAI',['../structcelebrasSpiritAI.html',1,'']]],
  ['cell',['Cell',['../structCell.html',1,'Cell'],['../structRegularGrid2D_1_1Cell.html',1,'RegularGrid2D&lt; T, Node, NodeCreatorFunc, PositionFunc &gt;::Cell']]],
  ['cellarea',['CellArea',['../structCellArea.html',1,'']]],
  ['celliterator',['CellIterator',['../classG3D_1_1PointHashGrid_1_1CellIterator.html',1,'G3D::PointHashGrid']]],
  ['cellobject',['CellObject',['../classG3D_1_1PointHashGrid_1_1CellIterator_1_1CellObject.html',1,'G3D::PointHashGrid::CellIterator']]],
  ['cellobjectguids',['CellObjectGuids',['../structCellObjectGuids.html',1,'']]],
  ['centercomparator',['CenterComparator',['../classG3D_1_1KDTree_1_1CenterComparator.html',1,'G3D::KDTree']]],
  ['chainhealingfullhealth',['ChainHealingFullHealth',['../classChainHealingFullHealth.html',1,'']]],
  ['chainhealingorder',['ChainHealingOrder',['../structChainHealingOrder.html',1,'']]],
  ['channel',['Channel',['../classChannel.html',1,'']]],
  ['channelmgr',['ChannelMgr',['../classChannelMgr.html',1,'']]],
  ['channelresetevent',['ChannelResetEvent',['../classChannelResetEvent.html',1,'']]],
  ['character_5fset',['character_set',['../structcharacter__set.html',1,'']]],
  ['characterdatabasecache',['CharacterDatabaseCache',['../classCharacterDatabaseCache.html',1,'']]],
  ['characterhandler',['CharacterHandler',['../classCharacterHandler.html',1,'']]],
  ['characterpetcache',['CharacterPetCache',['../structCharacterPetCache.html',1,'']]],
  ['charactersdatabaseworkerthread',['CharactersDatabaseWorkerThread',['../classCharactersDatabaseWorkerThread.html',1,'']]],
  ['chargemovementgenerator',['ChargeMovementGenerator',['../classChargeMovementGenerator.html',1,'']]],
  ['chargeunitselector',['ChargeUnitSelector',['../classChargeUnitSelector.html',1,'']]],
  ['charminfo',['CharmInfo',['../structCharmInfo.html',1,'']]],
  ['charset_5finfo_5fst',['charset_info_st',['../structcharset__info__st.html',1,'']]],
  ['charstartoutfitentry',['CharStartOutfitEntry',['../structCharStartOutfitEntry.html',1,'']]],
  ['chasemovementgenerator',['ChaseMovementGenerator',['../classChaseMovementGenerator.html',1,'']]],
  ['chatchannelsentry',['ChatChannelsEntry',['../structChatChannelsEntry.html',1,'']]],
  ['chatcommand',['ChatCommand',['../classChatCommand.html',1,'']]],
  ['chathandler',['ChatHandler',['../classChatHandler.html',1,'']]],
  ['check_5fauras_5fstack',['check_auras_stack',['../classcheck__auras__stack.html',1,'']]],
  ['chrclassesentry',['ChrClassesEntry',['../structChrClassesEntry.html',1,'']]],
  ['chrracesentry',['ChrRacesEntry',['../structChrRacesEntry.html',1,'']]],
  ['chuck',['Chuck',['../structChuck.html',1,'']]],
  ['chunk',['Chunk',['../structChunk.html',1,'Chunk'],['../structchunk.html',1,'chunk']]],
  ['cinematics_5fcaverns_5fof_5ftime_5fspirit_5fhealers',['cinematics_caverns_of_time_spirit_healers',['../classcinematics__caverns__of__time__spirit__healers.html',1,'']]],
  ['cinematics_5fcoldridge_5fvalley_5ffights',['cinematics_coldridge_valley_fights',['../classcinematics__coldridge__valley__fights.html',1,'']]],
  ['cinematics_5fcrossroads_5fcrowd',['cinematics_crossroads_crowd',['../classcinematics__crossroads__crowd.html',1,'']]],
  ['cinematics_5fduskwood_5fbattle',['cinematics_duskwood_battle',['../classcinematics__duskwood__battle.html',1,'']]],
  ['cinematics_5fgeneric_5fcharge',['cinematics_generic_charge',['../classcinematics__generic__charge.html',1,'']]],
  ['cinematics_5fnorthshire_5fvalley_5ffights',['cinematics_northshire_valley_fights',['../classcinematics__northshire__valley__fights.html',1,'']]],
  ['cinematics_5frun_5fblackrock',['cinematics_run_blackrock',['../classcinematics__run__blackrock.html',1,'']]],
  ['cinematics_5ftarren_5fmills_5fcharge_5falliance',['cinematics_tarren_mills_charge_alliance',['../classcinematics__tarren__mills__charge__alliance.html',1,'']]],
  ['cinematics_5ftarren_5fmills_5fcharge_5fhorde',['cinematics_tarren_mills_charge_horde',['../classcinematics__tarren__mills__charge__horde.html',1,'']]],
  ['cinematics_5ftarren_5fmills_5fcorpses',['cinematics_tarren_mills_corpses',['../classcinematics__tarren__mills__corpses.html',1,'']]],
  ['cinematics_5ftarren_5fmills_5ffights',['cinematics_tarren_mills_fights',['../classcinematics__tarren__mills__fights.html',1,'']]],
  ['cinematics_5ftheramore_5fcrowd',['cinematics_theramore_crowd',['../classcinematics__theramore__crowd.html',1,'']]],
  ['cinematics_5fvalley_5fof_5ftrials_5fcharge_5fhorde',['cinematics_valley_of_trials_charge_horde',['../classcinematics__valley__of__trials__charge__horde.html',1,'']]],
  ['cinematicsequencesentry',['CinematicSequencesEntry',['../structCinematicSequencesEntry.html',1,'']]],
  ['cinematicstuff',['CinematicStuff',['../classCinematicStuff.html',1,'']]],
  ['cinematicwaypointentry',['CinematicWaypointEntry',['../structCinematicWaypointEntry.html',1,'']]],
  ['classcallinfo',['ClassCallInfo',['../structClassCallInfo.html',1,'']]],
  ['classlevellockable',['ClassLevelLockable',['../classMaNGOS_1_1ClassLevelLockable.html',1,'MaNGOS']]],
  ['claw_5ftentacleai',['claw_tentacleAI',['../structclaw__tentacleAI.html',1,'']]],
  ['clawtentacle',['clawTentacle',['../structclawTentacle.html',1,'']]],
  ['cleandamage',['CleanDamage',['../structCleanDamage.html',1,'']]],
  ['clicommandholder',['CliCommandHolder',['../structCliCommandHolder.html',1,'']]],
  ['clientpktheader',['ClientPktHeader',['../structClientPktHeader.html',1,'']]],
  ['clihandler',['CliHandler',['../classCliHandler.html',1,'']]],
  ['clirunnable',['CliRunnable',['../classCliRunnable.html',1,'']]],
  ['code',['code',['../structcode.html',1,'']]],
  ['collisiondetection',['CollisionDetection',['../classG3D_1_1CollisionDetection.html',1,'G3D']]],
  ['color1',['Color1',['../classG3D_1_1Color1.html',1,'G3D']]],
  ['color1uint8',['Color1uint8',['../classG3D_1_1Color1uint8.html',1,'G3D']]],
  ['color3',['Color3',['../classG3D_1_1Color3.html',1,'G3D']]],
  ['color3uint8',['Color3uint8',['../classG3D_1_1Color3uint8.html',1,'G3D']]],
  ['color4',['Color4',['../classG3D_1_1Color4.html',1,'G3D']]],
  ['color4uint8',['Color4uint8',['../classG3D_1_1Color4uint8.html',1,'G3D']]],
  ['combatstopwithpetshelper',['CombatStopWithPetsHelper',['../structCombatStopWithPetsHelper.html',1,'']]],
  ['commoninitializer',['CommonInitializer',['../structMovement_1_1CommonInitializer.html',1,'Movement']]],
  ['comp_5fctx_5fst',['comp_ctx_st',['../structcomp__ctx__st.html',1,'']]],
  ['comp_5fmethod_5fst',['comp_method_st',['../structcomp__method__st.html',1,'']]],
  ['comparator',['Comparator',['../classG3D_1_1KDTree_1_1Comparator.html',1,'G3D::KDTree']]],
  ['conditionentry',['ConditionEntry',['../classConditionEntry.html',1,'']]],
  ['conditiontable',['ConditionTable',['../structConditionTable.html',1,'']]],
  ['conduit',['Conduit',['../classG3D_1_1Conduit.html',1,'G3D']]],
  ['cone',['Cone',['../classG3D_1_1Cone.html',1,'G3D']]],
  ['conf_5fmethod_5fst',['conf_method_st',['../structconf__method__st.html',1,'']]],
  ['conf_5fst',['conf_st',['../structconf__st.html',1,'']]],
  ['conf_5fvalue',['CONF_VALUE',['../structCONF__VALUE.html',1,'']]],
  ['config',['Config',['../classConfig.html',1,'']]],
  ['config_5fs',['config_s',['../structconfig__s.html',1,'']]],
  ['confusedmovementgenerator',['ConfusedMovementGenerator',['../classConfusedMovementGenerator.html',1,'']]],
  ['conjunction',['conjunction',['../structnlohmann_1_1detail_1_1conjunction.html',1,'nlohmann::detail']]],
  ['conjunction_3c_20b1_20_3e',['conjunction&lt; B1 &gt;',['../structnlohmann_1_1detail_1_1conjunction_3_01B1_01_4.html',1,'nlohmann::detail']]],
  ['conjunction_3c_20b1_2c_20bn_2e_2e_2e_20_3e',['conjunction&lt; B1, Bn... &gt;',['../structnlohmann_1_1detail_1_1conjunction_3_01B1_00_01Bn_8_8_8_01_4.html',1,'nlohmann::detail']]],
  ['containermaplist',['ContainerMapList',['../structContainerMapList.html',1,'']]],
  ['containermaplist_3c_20grid_5fobject_5ftypes_20_3e',['ContainerMapList&lt; GRID_OBJECT_TYPES &gt;',['../structContainerMapList.html',1,'']]],
  ['containermaplist_3c_20h_20_3e',['ContainerMapList&lt; H &gt;',['../structContainerMapList.html',1,'']]],
  ['containermaplist_3c_20object_5ftypes_20_3e',['ContainerMapList&lt; OBJECT_TYPES &gt;',['../structContainerMapList.html',1,'']]],
  ['containermaplist_3c_20t_20_3e',['ContainerMapList&lt; T &gt;',['../structContainerMapList.html',1,'']]],
  ['containermaplist_3c_20typelist_3c_20h_2c_20t_20_3e_20_3e',['ContainerMapList&lt; TypeList&lt; H, T &gt; &gt;',['../structContainerMapList_3_01TypeList_3_01H_00_01T_01_4_01_4.html',1,'']]],
  ['containermaplist_3c_20typenull_20_3e',['ContainerMapList&lt; TypeNull &gt;',['../structContainerMapList_3_01TypeNull_01_4.html',1,'']]],
  ['containermaplist_3c_20world_5fobject_5ftypes_20_3e',['ContainerMapList&lt; WORLD_OBJECT_TYPES &gt;',['../structContainerMapList.html',1,'']]],
  ['containerunorderedmap',['ContainerUnorderedMap',['../structContainerUnorderedMap.html',1,'']]],
  ['containerunorderedmap_3c_20allmapstoredobjecttypes_2c_20objectguid_20_3e',['ContainerUnorderedMap&lt; AllMapStoredObjectTypes, ObjectGuid &gt;',['../structContainerUnorderedMap.html',1,'']]],
  ['containerunorderedmap_3c_20h_2c_20key_5ftype_20_3e',['ContainerUnorderedMap&lt; H, KEY_TYPE &gt;',['../structContainerUnorderedMap.html',1,'']]],
  ['containerunorderedmap_3c_20object_5ftypes_2c_20key_5ftype_20_3e',['ContainerUnorderedMap&lt; OBJECT_TYPES, KEY_TYPE &gt;',['../structContainerUnorderedMap.html',1,'']]],
  ['containerunorderedmap_3c_20t_2c_20key_5ftype_20_3e',['ContainerUnorderedMap&lt; T, KEY_TYPE &gt;',['../structContainerUnorderedMap.html',1,'']]],
  ['containerunorderedmap_3c_20typelist_3c_20h_2c_20t_20_3e_2c_20key_5ftype_20_3e',['ContainerUnorderedMap&lt; TypeList&lt; H, T &gt;, KEY_TYPE &gt;',['../structContainerUnorderedMap_3_01TypeList_3_01H_00_01T_01_4_00_01KEY__TYPE_01_4.html',1,'']]],
  ['containerunorderedmap_3c_20typenull_2c_20key_5ftype_20_3e',['ContainerUnorderedMap&lt; TypeNull, KEY_TYPE &gt;',['../structContainerUnorderedMap_3_01TypeNull_00_01KEY__TYPE_01_4.html',1,'']]],
  ['continentasyncupdater',['ContinentAsyncUpdater',['../classContinentAsyncUpdater.html',1,'']]],
  ['controls_5fand_5fmovementtest',['controls_and_movementTest',['../classcontrols__and__movementTest.html',1,'']]],
  ['controls_5fleave_5fcombattest',['controls_leave_combatTest',['../classcontrols__leave__combatTest.html',1,'']]],
  ['controls_5fsheep_5ffear_5fstack',['controls_sheep_fear_stack',['../classcontrols__sheep__fear__stack.html',1,'']]],
  ['convertattributes',['ConvertAttributes',['../structG3D_1_1ConvertAttributes.html',1,'G3D']]],
  ['convexpolygon',['ConvexPolygon',['../classG3D_1_1ConvexPolygon.html',1,'G3D']]],
  ['convexpolygon2d',['ConvexPolygon2D',['../classG3D_1_1ConvexPolygon2D.html',1,'G3D']]],
  ['convexpolyhedron',['ConvexPolyhedron',['../classG3D_1_1ConvexPolyhedron.html',1,'G3D']]],
  ['convexvolume',['ConvexVolume',['../structConvexVolume.html',1,'']]],
  ['convexvolumetool',['ConvexVolumeTool',['../classConvexVolumeTool.html',1,'']]],
  ['coordinateframe',['CoordinateFrame',['../classG3D_1_1CoordinateFrame.html',1,'G3D']]],
  ['coordpair',['CoordPair',['../structCoordPair.html',1,'']]],
  ['coordpair_3c_2064_20_3e',['CoordPair&lt; 64 &gt;',['../structCoordPair.html',1,'']]],
  ['coordpair_3c_2864_20_2a16_29_20_3e',['CoordPair&lt;(64 *16) &gt;',['../structCoordPair.html',1,'']]],
  ['coords',['Coords',['../structCoords.html',1,'']]],
  ['corpse',['Corpse',['../classCorpse.html',1,'']]],
  ['corruptedwhelpai',['CorruptedWhelpAI',['../structCorruptedWhelpAI.html',1,'']]],
  ['corrupttext',['CorruptText',['../classG3D_1_1AnyVal_1_1CorruptText.html',1,'G3D::AnyVal']]],
  ['counter',['counter',['../classMovement_1_1counter.html',1,'Movement']]],
  ['createoncallback',['CreateOnCallBack',['../classMaNGOS_1_1CreateOnCallBack.html',1,'MaNGOS']]],
  ['createusingmalloc',['CreateUsingMalloc',['../classMaNGOS_1_1CreateUsingMalloc.html',1,'MaNGOS']]],
  ['creature',['Creature',['../classCreature.html',1,'']]],
  ['creature_5fspawn_5ffankrissai',['creature_spawn_fankrissAI',['../structcreature__spawn__fankrissAI.html',1,'']]],
  ['creature_5ftype',['creature_type',['../structcreature__type.html',1,'']]],
  ['creature_5fvekniss_5fhatchlingai',['creature_vekniss_hatchlingAI',['../structcreature__vekniss__hatchlingAI.html',1,'']]],
  ['creatureai',['CreatureAI',['../classCreatureAI.html',1,'']]],
  ['creatureaifactory',['CreatureAIFactory',['../structCreatureAIFactory.html',1,'']]],
  ['creatureaispellsentry',['CreatureAISpellsEntry',['../structCreatureAISpellsEntry.html',1,'']]],
  ['creaturecreatepos',['CreatureCreatePos',['../structCreatureCreatePos.html',1,'']]],
  ['creaturedata',['CreatureData',['../structCreatureData.html',1,'']]],
  ['creaturedataaddon',['CreatureDataAddon',['../structCreatureDataAddon.html',1,'']]],
  ['creaturedisplayinfoentry',['CreatureDisplayInfoEntry',['../structCreatureDisplayInfoEntry.html',1,'']]],
  ['creaturedisplayinfoextraentry',['CreatureDisplayInfoExtraEntry',['../structCreatureDisplayInfoExtraEntry.html',1,'']]],
  ['creatureescortdata',['CreatureEscortData',['../structCreatureEscortData.html',1,'']]],
  ['creatureeventai',['CreatureEventAI',['../classCreatureEventAI.html',1,'']]],
  ['creatureeventai_5fevent',['CreatureEventAI_Event',['../structCreatureEventAI__Event.html',1,'']]],
  ['creatureeventaiholder',['CreatureEventAIHolder',['../structCreatureEventAIHolder.html',1,'']]],
  ['creatureeventaimgr',['CreatureEventAIMgr',['../classCreatureEventAIMgr.html',1,'']]],
  ['creaturefamilyentry',['CreatureFamilyEntry',['../structCreatureFamilyEntry.html',1,'']]],
  ['creaturegroup',['CreatureGroup',['../classCreatureGroup.html',1,'']]],
  ['creaturegroupmember',['CreatureGroupMember',['../structCreatureGroupMember.html',1,'']]],
  ['creaturegroupsmanager',['CreatureGroupsManager',['../classCreatureGroupsManager.html',1,'']]],
  ['creatureinfo',['CreatureInfo',['../structCreatureInfo.html',1,'']]],
  ['creaturelastsearcher',['CreatureLastSearcher',['../structMaNGOS_1_1CreatureLastSearcher.html',1,'MaNGOS']]],
  ['creaturelinkingholder',['CreatureLinkingHolder',['../classCreatureLinkingHolder.html',1,'']]],
  ['creaturelinkinginfo',['CreatureLinkingInfo',['../structCreatureLinkingInfo.html',1,'']]],
  ['creaturelinkingmgr',['CreatureLinkingMgr',['../classCreatureLinkingMgr.html',1,'']]],
  ['creaturelistsearcher',['CreatureListSearcher',['../structMaNGOS_1_1CreatureListSearcher.html',1,'MaNGOS']]],
  ['creaturelocale',['CreatureLocale',['../structCreatureLocale.html',1,'']]],
  ['creaturemodeldataentry',['CreatureModelDataEntry',['../structCreatureModelDataEntry.html',1,'']]],
  ['creaturemodelinfo',['CreatureModelInfo',['../structCreatureModelInfo.html',1,'']]],
  ['creaturerelocationnotifier',['CreatureRelocationNotifier',['../structMaNGOS_1_1CreatureRelocationNotifier.html',1,'MaNGOS']]],
  ['creaturerespawndeleteworker',['CreatureRespawnDeleteWorker',['../structCreatureRespawnDeleteWorker.html',1,'']]],
  ['creaturesearcher',['CreatureSearcher',['../structMaNGOS_1_1CreatureSearcher.html',1,'MaNGOS']]],
  ['creaturespelldataentry',['CreatureSpellDataEntry',['../structCreatureSpellDataEntry.html',1,'']]],
  ['creaturespellsentry',['CreatureSpellsEntry',['../structCreatureSpellsEntry.html',1,'']]],
  ['creaturetypeentry',['CreatureTypeEntry',['../structCreatureTypeEntry.html',1,'']]],
  ['creaturewaveentry',['CreatureWaveEntry',['../classCreatureWaveEntry.html',1,'']]],
  ['creaturewithdbguidcheck',['CreatureWithDbGUIDCheck',['../classMaNGOS_1_1CreatureWithDbGUIDCheck.html',1,'MaNGOS']]],
  ['creatureworker',['CreatureWorker',['../structMaNGOS_1_1CreatureWorker.html',1,'MaNGOS']]],
  ['crowdtool',['CrowdTool',['../classCrowdTool.html',1,'']]],
  ['crowdtoolparams',['CrowdToolParams',['../structCrowdToolParams.html',1,'']]],
  ['crowdtoolstate',['CrowdToolState',['../classCrowdToolState.html',1,'']]],
  ['crtmemorymanager',['CRTMemoryManager',['../classG3D_1_1CRTMemoryManager.html',1,'G3D']]],
  ['crypto',['Crypto',['../classG3D_1_1Crypto.html',1,'G3D']]],
  ['crypto_5fdynlock',['CRYPTO_dynlock',['../structCRYPTO__dynlock.html',1,'']]],
  ['crypto_5fex_5fdata_5ffunc_5fst',['crypto_ex_data_func_st',['../structcrypto__ex__data__func__st.html',1,'']]],
  ['crypto_5fex_5fdata_5fst',['crypto_ex_data_st',['../structcrypto__ex__data__st.html',1,'']]],
  ['crypto_5fthreadid_5fst',['crypto_threadid_st',['../structcrypto__threadid__st.html',1,'']]],
  ['csymbolinfopackage',['CSymbolInfoPackage',['../structCSymbolInfoPackage.html',1,'']]],
  ['ct_5fdata_5fs',['ct_data_s',['../structct__data__s.html',1,'']]],
  ['cthunai',['cthunAI',['../structcthunAI.html',1,'']]],
  ['cthunportaltentacle',['cthunPortalTentacle',['../structcthunPortalTentacle.html',1,'']]],
  ['cthuntentacle',['cthunTentacle',['../structcthunTentacle.html',1,'']]],
  ['cylinder',['Cylinder',['../classG3D_1_1Cylinder.html',1,'G3D']]]
];
